Avoid boost bug
alicevision/CCTag pull request #153
Opened 2021-02-05 12:53 UTC by griwodz

## Description

Avoids the constexpr bug encountered with boost 1.73 by moving the boost::accumulator into some utility classes.
By drawing values from a simple std::vector instead of advanced classes, the bug is apparently not triggered.

## Features list

## Implementation remarks

2021-02-05 13:04 UTC, griwodz commented
@fabiencastan I don't know why, but the Accumulator bug goes doesn't appear when I collect the data points in a std::vector first.

2021-02-12 09:26 UTC, griwodz commented
It may not be the high-performance solution to solve the boost::accumulator problem, but it seems that the accumulator can be used by copying all values into a std::vector first and hiding the accumulator inside a separate file. Does it make sense to pay the price?

2021-02-14 17:16 UTC, simogasp requested changes
I'm all in for hiding implementation in a cpp.
Another non-exclusive way is to switch to c++14. What are your thoughts about that? (i mean in general, wrt the effects on cuda etc, unrelated to the issue at hand)
I pushed a branch with the c++14 enabled and it works without issues, if u wanna test and take a look

2021-02-14 17:16 UTC, simogasp commented on src/cctag/utils/Accum.cpp
> +    for( auto f : acc ) v.operator()(f);
maybe can be done without copy:
```c++
#include <functional>

bacc::accumulator_set< float, bacc::features< bacc::tag::variance > > v;
for_each(acc.begin(), acc.end(), std::bind<void>(std::ref(v), _1));
return bacc::variance( v );
```
see here https://stackoverflow.com/a/7616820

2021-02-14 17:16 UTC, simogasp commented on src/cctag/utils/Accum.hpp
> +#define _CCTAG_ACCUMULATOR
```suggestion
#pragma once
```

2021-02-14 17:16 UTC, simogasp commented on src/cctag/utils/Accum.hpp
> +    VarianceAccumulator( ) { }
```suggestion
    VarianceAccumulator() = default;
```

2021-02-14 17:16 UTC, simogasp commented on src/cctag/utils/Accum.hpp
> +    MeanAccumulator( ) { }
```suggestion
    MeanAccumulator() = default;
```

2021-02-14 17:16 UTC, simogasp commented on src/cctag/utils/Accum.hpp
> +    LMeanAccumulator( ) { }
```suggestion
    LMeanAccumulator() = default;
```

2021-02-15 08:29 UTC, griwodz commented
@simogasp If we can agree with Fabien about C++14, I'm happy and we can just discard this PR. Can we assume that C++14 compilers are everywhere?

It would be nice to have full C++17 support with working implementations of <execution> and templates like std::reduce and std::transform_reduce. It will probably take a while until we get there.

2021-02-15 09:40 UTC, fabiencastan commented
Yes, I think we should be able to move to C++-14 on all repositories (following the vfxplatform.com recommendations).

2021-02-15 14:11 UTC, griwodz commented
OK, so let's go for c++14 it then, and forget about this PR.

2021-02-15 14:11 UTC, closed without merging

2021-02-15 16:51 UTC, simogasp commented
I forgot that we already switched to c++14 in popsift, well one less to be done :-)

2021-02-15 17:00 UTC, griwodz commented
Popsift uses the C++ versions only to make the CUDA SDKs happy, there is little potential for conflicts with Boost and the like.